
Turn 2
================================================================
error: failed to decode bot message: "T" (at position 1)
Last input received was:
Traceback (most recent call last):
  File "MyBot.py", line 14, in <module>
    bot.run()
  File "D:\CNN project\SVM\SVMBot.py", line 77, in run
    for di in random.shuffle(ship.position.get_surrounding_cardinals()):
TypeError: 'NoneType' object is not iterable

